name: 'Deploy App to S3'
on: 
  push:
    branches:
      - second #Uniquement sur la branche main
      # Dans ce cas sur toutes les branches [push]

jobs:
  deployement: #juste un nom 
    runs-on: ubuntu-latest # provide temporary  ubuntu instance
    steps:  #
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli
    - name: Configure
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region eu-west-3

    - name: check if bucket exist
      run: |
        if aws s3api head-bucket $AWS_BUCKET_NAME; then
          echo "Bucket exists."
        else 
          echo "Bucket does not exist. Stopping the pipeline."
          exit 1
        fi
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}

 # - name: List directory
    #   run: |
    #     ls -la
    # - name: create new file
    #   run: |
    #     touch newfile.txt
    # - name: List directory again
    #   run: |
    #     ls -la